<?php    

return array(   
    array("NDC"=>"15019",
	      "min_chars_count"=> 14,
 		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Tismi BV",
	),
    array("NDC"=>"1511",
	      "min_chars_count"=> 14,
 		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"1512",
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"1514",
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"1515",
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"1516",
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"1517",
		  "min_chars_count"=> 14,
	      "max_chars_count"=> 14,
	      "type"=>"Mobile services",
	      "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"15180",
 	      "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"15181",
	      "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"1520",
      	  "min_chars_count"=> 14,
		  "max_digits_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Vodafone GmbH"
	),
    array("NDC"=>"1521",
		  "min_chars_count"=> 14,
	      "max_chars_count"=> 14,
	      "type"=>"Mobile services",
	      "name"=>"Lycamobile Europe Ltd."
	),
    array("NDC"=>"1522",
	      "min_chars_count"=> 14,
 		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Vodafone GmbH"
	),
    array("NDC"=>"1523",
	      "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Vodafone GmbH"
	),
    array("NDC"=>"1525",
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14, 
		  "type"=>"Mobile services",
		  "name"=>"Vodafone GmbH"
	),
    array("NDC"=>"1526",
	      "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Vodafone GmbH"
	),
    array("NDC"=>"1529",
	      "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Vodafone GmbH / MVNO Truphone GmbH"
	),
    array("NDC"=>"15310",
	     "min_chars_count"=> 14,
		 "max_chars_count"=> 14,
		 "type"=>"Mobile services",
		 "name"=>"MTEL Deutschland GmbH"
	),
    array("NDC"=>"15510",
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14, 
		  "type"=>"Mobile services",
		  "name"=>"Lebara Limited"
	),
    array("NDC"=>"15511",
	      "min_digits_count"=> 14,
		  "max_digits_count"=> 14,
		  "type"=>"Mobile services", 
		  "name"=>"Lebara Limited"
	),
    array("NDC"=>"15566",
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14, 
		  "type"=>"Mobile services", 
		  "name"=>"Drillisch Online AG"
	),
    array("NDC"=>"15630",
     	  "min_chars_count"=> 14,
		  "max_digits_count"=> 14, 
		  "type"=>"Mobile services",
		  "name"=>"multiConnect GmbH"
	),
    array("NDC"=>"15678", 
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14, 
		  "type"=>"Mobile services",
		  "name"=>"Argon Networks UG"
	),
    array("NDC"=>"15679", 
 		  "min_chars_count"=> 14, 
		  "max_digits_count"=> 14, 
		  "val3"=>"Mobile services",
		  "name"=>"Argon Networks UG"
	),
    array("NDC"=>"1570",
		  "min_chars_count"=> 14, 
		  "max_chars_count"=> 14, 
		  "type"=>"Mobile services", 
		  "name"=>"Telefónica Germany GmbH  Co. OHG (former: E-Plus Mobilfunk GmbH) /MVNO"
	),
    array("NDC"=>"1573",
		  "min_chars_count"=> 14, 
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services", 
		  "name"=>"Telefónica Germany GmbH  Co. OHG(former: E-Plus Mobilfunk GmbH)"
	),
    array("NDC"=>"1575", 
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Telefónica Germany GmbH  Co. OHG (former: E-Plus Mobilfunk GmbH)"
	),
    array("NDC"=>"1577",
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services", 
		  "name"=>"Telefónica Germany GmbH  Co. OHG (former: E-Plus Mobilfunk GmbH)"
	),
    array("NDC"=>"1578",
		  "min_chars_count"=> 14, 
		  "max_chars_count"=> 14,
		  "val3"=>"Mobile services", 
		  "name"=>"Telefónica Germany GmbH  Co. OHG (former: E-Plus Mobilfunk GmbH)"
	),
    array("NDC"=>"1579",
	      "min_chars_count"=> 14, 
		  "max_digits_count"=> 14,
		  "type"=>"Mobile services", 
		  "name"=>"Telefónica Germany GmbH  Co. OHG (former: E-Plus Mobilfunk GmbH) /MVNO Sipgate Wireless GmbH"
	),
    array("NDC"=>"15888",
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14, 
		  "type"=>"Mobile services",
		  "name"=>"TelcoVillage GmbH"
	),
    array("NDC"=>"1590",
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14, 
		  "type"=>"Mobile services", 
		  "name"=>"Telefónica Germany GmbH & Co. OHG"
	),
    array("NDC"=>"1600",
		  "min_chars_count"=> 13, 
	      "max_digits_count"=> 13,
	      "type"=>"Mobile services",
	      "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"1601",
		  "min_chars_count"=> 13, 
	      "max_chars_count"=> 13,
	      "type"=>"Mobile services",
	      "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"1602",
		  "min_chars_count"=> 13, 
	      "max_digits_count"=> 13,
	      "type"=>"Mobile services",
	      "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"1603",
		  "min_chars_count"=> 13, 
	      "max_chars_count"=> 13,
	      "type"=>"Mobile services",
	      "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"1604",
		  "min_chars_count"=> 13, 
	      "max_chars_count"=> 13,
	      "type"=>"Mobile services",
	      "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"1605",
		  "min_chars_count"=> 13, 
	      "max_digits_count"=> 13,
	      "type"=>"Mobile services",
	      "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"1606",
		  "min_chars_count"=> 13, 
	      "max_chars_count"=> 13,
	      "type"=>"Mobile services",
	      "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"1607",
		  "min_chars_count"=> 13, 
	      "max_chars_count"=> 13,
	      "type"=>"Mobile services",
	      "name"=>"Telekom Deutschland GmbH"
	),	
    array("NDC"=>"1608",
		  "min_chars_count"=> 13, 
	      "max_digits_count"=> 13,
	      "type"=>"Mobile services",
	      "name"=>"Telekom Deutschland GmbH"
	),	
    array("NDC"=>"1609",
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"162",
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Vodafone GmbH"
	),
    array("NDC"=>"163",
		  "min_chars_count"=> 13,
		  "max_chars_count"=> 13,
		  "type"=>"Mobile services",
		  "name"=>"E-Plus Mobilfunk GmbH"
	),
    array("NDC"=>"170",
		  "min_chars_count"=> 13,
		  "max_chars_count"=> 13,
		  "type"=>"Mobile services",
		  "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"171",
		  "min_chars_count"=> 13,
		  "max_chars_count"=> 13,
		  "type"=>"Mobile services",
		  "name"=>"Telekom Deutschland GmbH"
	),
    array("NDC"=>"172",
		  "min_chars_count"=> 13,
		  "max_chars_count"=> 13,
		  "type"=>"Mobile services",
		  "name"=>"Vodafone GmbH"
	),
    array("NDC"=>"173",
		  "min_chars_count"=> 13,
		  "max_digits_count"=> 13,
		  "type"=>"Mobile services",
		  "name"=>"Vodafone GmbH"
	),
    array("NDC"=>"174",
		  "min_chars_count"=> 13,
	 	  "max_chars_count"=> 13,
		  "type"=>"Mobile services",
		  "name"=>"Vodafone GmbH"
	),
    array("NDC"=>"175",
		  "min_chars_count"=> 13,
		  "max_chars_count"=> 13,
		  "type"=>"Mobile services",
		  "name"=>"Telekom Deutschland GmbH"
		),
    array("NDC"=>"176",
		  "min_chars_count"=> 14,
		  "max_chars_count"=> 14,
		  "type"=>"Mobile services",
		  "name"=>"Telefónica Germany GmbH & Co. OHG"
	),
    array("NDC"=>"177",
		  "min_chars_count"=> 13,
		  "max_chars_count"=> 13,
		  "type"=>"Mobile services",
		  "name"=>"Telefónica Germany GmbH  Co. OHG (former: E-Plus Mobilfunk GmbH)"
	),
    array("NDC"=>"178", 
		  "min_chars_count"=> 13, 
		  "max_chars_count"=> 13,
		  "type"=>"Mobile services", 
		  "name"=>"Telefónica Germany GmbH  Co. OHG (former: E-Plus Mobilfunk GmbH)"
	),
    array("NDC"=>"179", 
		  "min_chars_count"=> 13, 
		  "max_chars_count"=> 13, 
		  "type"=>"Mobile services",
		  "name"=>"Telefónica Germany GmbH & Co. OHG"
	)
);
